= leaf(1)

== NAME

leaf - development workspace manager

== SYNOPSIS

*leaf* [*--non-interactive*] [*-w* _WORKSPACE_] *_COMMAND_* [*-v*|*-q*] [options...]

*leaf* *-V|--version* # Display version

*leaf* [*_COMMAND_*] *-h|--help* # Display help

== DESCRIPTION

*leaf* is a workspace management tool, allowing to setup and configure a development environment
based on packages.

== OPTIONS

These options are generic for all *leaf* commands

*-v|--verbose*::

Toggle output to verbose mode (more details)

*-q|--quiet*::

Toggle output to quiet mode (less details)

*-V|--version*::

Display *leaf* current version and exit; same as *leaf version* command

*-h|--help*::

Display command help and exit

*--non-interactive*::

Answer the default choice to every asked question

*-w|--workspace _WORKSPACE_*::

Use specified workspace path instead of looking in the current directory structure

== COMMANDS

The different actions that can be performed with *leaf* are available through commands.
Use *leaf help _COMMAND_* to get documentation for a specific action.

=== High level commands

*help*::

Display *leaf* manual pages

*search*::

Search for available packages

*setup*::

All in one command to setup a workspace, and configure a profile inside

*select*::

Change to a different active profile in the current workspace

*shell*::

Spawn a shell with the development environment loaded in the current workspace

*status*::

Display information about the current workspace status

*update*::

Update the current profile packages configuration

*getsrc*::

Toggle packages used in the current profile in "source code" mode

=== Low level commands

*version*::

Displays *leaf* current version

*config*::

Setup *leaf* configuration

*remote*::

Manage remotes (package repositories) from which *leaf* can install packages

*feature*::

Manage "features", used to tweak package dependencies

*init*::

Initialize workspace directory

*profile*::

Manage profiles in a workspace

*package*::

Manage packages (out of workspace)

*env*::

Display and set environment variables

== Other help pages

*colors*::

Documentation page on how to configure colors rendering with *leaf*

*others*::

Other help pages are also contributed; see *leaf help --list* to get all the available help pages
