= leaf(1)

== NAME

leaf - development workspace manager

== DESCRIPTION

Leaf is a workspace manager that will download, install and configure the required software packages
for a development environment.

To list all available leaf commands see *leaf help --list*

== LEAF COMMANDS

Informational Leaf Commands
[listing]
help      Displays this page and other help commands. (i.e.; leaf help <command>)
version   Displays the version of Leaf

Initialize a workspace/profile and download a package for your target (see also: *leaf help legato-start*)
[listing]
search    Search for a package for your target
setup     Setup a workspace (if not created), create/setup a profile and download packages
shell     Enter into a shell configured for your profile and environment


Manage your Profile
[listing]
status    List your current profiles and their status
select    Switch between multiple profiles
update    Update(upgrade/downgrade) a profile to another version of a package
profile   Manage your profiles: rename, delete, sync


Configure a profile to use the source or binary version of a package (see also: *leaf help legato-source*)
[listing]
getsrc    Switch to the source version of a package (if available)


Manage your Leaf Environment
[listing]
colors    Change to a different color theme
env       Create, set, and remove environment variables
config    Manage the configuration of leaf
feature   List and toggle features allowing to configure packages behavior


Manage the repositories for your packages. (see also: *leaf help legato-workflow*)
[listing]
remote    Add, remove and manage the list of remote repositories


Use tools and binaries
[listing]
run       List and execute binaries/tools bundled in installed packages


Manage packages
[listing]
package   List, install, uninstall, upgrade packages (independently from any workspace)


Build packages
[listing]
manifest  Describe how to write a leaf package manifest
build     Build manifests, packages and indexes


== OPTIONS
[listing]
leaf [--non-interactive] [-w <workspace>] <command> [-v|-q] [options...]
leaf -V|--version             Displays version
leaf [<command>] -h|--help    Display help

=== OPTIONAL ARGUMENTS
[listing]
-v, --verbose                 Increase the level of logging for the command
-q, --quiet                   Remove all command output except meaningful information
--non-interactive             Answer the default choice to every question asked
-w, --workspace <workspace>   Use the specified workspace path

