= leaf-feature(1)

== NAME

leaf-feature - toggle features for packages

== SYNOPSIS

*leaf* *feature* [*list*]

*leaf* *feature* *toggle* _FEATURE_ _VALUE_ [*--user*|*--workspace*|*--profile*]

*leaf* *feature* *query* _FEATURE_

== DESCRIPTION

*leaf feature* command allows to query and toggle feature values. A *leaf* feature is a configurable
value provided by packages, it allows a user to tune package behavior and installed content. i.e.;
when a library distributed through a *leaf* package can be used either in binary mode
(pre-compiled) or in source mode (if one want to make some customization and rebuild).

Feature values are stored as an environment variable, so it means that the feature system has the
flexibility to be configured either in the user, workspace, or profile scope (see *leaf env* command).

== SUB-COMMANDS

*list*::

Lists the available features for available and installed packages. (default option)
  - default: displays a table with _FEATURE_ id, some description text explaining the feature
    purpose, and a list of possible _VALUE_ items
  - *-v*: as above, plus the name of variable used to store the current feature _VALUE_
  - *-q*: displays only _FEATURE_ id list
+
Note that the *list* command must be specified if one of the *-q*|*-v* option is specified.

*query*::

Checks the current status of the _FEATURE_. Displays the current _VALUE_ of the feature, according
to the current user/workspace/profile configuration.

*toggle*::

Changes the _FEATURE_ to _VALUE_. By default, the toggled value will be stored in the current
profile.

== OPTIONS

_FEATURE_::

A feature identifier. List of available _FEATURE_ items is returned by *list* command.

_VALUE_::

A feature value. List of available _VALUE_ items for a given _FEATURE_ is returned by *list* command.

*--user|--workspace|--profile*::

Used to modify the scope option. Used with the *toggle* command, and allows to specify which scope
needs to be configured for the required feature. Allows users to enable a feature across all
workspaces (if *--user* is used), across all profiles of a given workspace (if *--workspace* is
used), or specifically to the current profile (if *--profile* is used; default if not specified).

== EXAMPLES

Get features list::

Valid wherever you are:
+
*leaf feature list*

Get feature status::

Checks if the feature is enabled in the current context:
+
*leaf feature query someFeature*

Sets the feature value for current profile::

Assumes you're in an existing workspace:
+
*leaf feature toggle someFeature someValue*

Sets the feature value for all workspaces::

Valid wherever you are:
+
*leaf feature toggle someFeature someValue --user*

== BEHAVIOR

*leaf feature toggle* is an atomic command that will just set environment variable matching with
the required feature and value. If this variable is used to modify package dependencies, the profile
will have to be provisioned (see *leaf profile sync*).

== SEE ALSO

*leaf env*, *leaf profile*
