= leaf-config(1)

== NAME

leaf-config - configure and customize leaf options

== SYNOPSIS

*leaf* *config* [*--root* _PACKAGES_ROOT_]

== DESCRIPTION

*leaf config* allows users to configure the leaf tool behavior.

If used without specifying any option, the command will simply outputs the location of the current
configuration file (cf _LEAF_CONFIG_ variable description below).

If used with **--root** option, the command will set the packages install location.

Beyond this command, the leaf tool is also configured through a set of environment variables,
described in this page as well.

== OPTIONS

*--root* _PACKAGES_ROOT_::

Sets the location where packages are installed. A package named _myPackage_1.0_ will be extracted
and installed in the _PACKAGES_ROOT/myPackage_1.0_ folder. Default value for this parameter is
*$HOME/.leaf*

== VARIABLES

The following environment variables can be used to configure the leaf tool behavior.

=== _LEAF_CONFIG_

Location for the leaf configuration folder. Default value is *$HOME/.config/leaf*

_LEAF_CONFIG_ stores the following files/folders:

*config.json*::

The main leaf configuration file which stores:
+
    - the packages root install folder  (cf *--root* option above)
    - the configured remotes list (see *leaf remote*)
    - the user's global environment (see *leaf env*)
+
Global configuration for *leaf* behavior is a combination of the default configuration
file with the *config.json* file present in the user configuration folder (if any).
+
Leaf will search for *config.json* in the following order:
*/etc/leaf/*, */usr/share/leaf/* and then *$HOME/.local/share/leaf/*
+
Modifying the default configuration (e.g. disabling a remote present in the
default configuration) will be stored in the user *config.json* file and
override any default values.
+
Note: in order to reset to the default configuration,
delete the *config.json* file from the user configuration folder.

*themes.ini*::

Contains the colors themes definition (see *leaf help colors* help page)
+
If the *themes.ini* file is not found in the user configuration folder,
leaf will search for *themes.ini* in the following folders:
*/etc/leaf/*, */usr/share/leaf/* and then *$HOME/.local/share/leaf/*
+
Note: in order to reset to the default color theme configuration,
delete the *themes.ini* file from the user configuration folder.

*gpg*::

The gpg keyring folder that contains the keyrings used by leaf for remotes gpg signing.

=== _LEAF_CACHE_

Location for the leaf download cache. Default value: *$HOME/.cache/leaf*

Location of cached information and may contain:

    - info from remote indexes
    - package artifacts before install

=== _LEAF_TIMEOUT_

Duration (in seconds) of the download timeout. Default value is *5*

Timeout that leaf waits to download data when the remote falls into an inactive state.

== SEE ALSO

*leaf remote*, *leaf env*, *leaf help colors*
