= leaf(1)

== NAME

leaf - development workspace manager

== DESCRIPTION

Leaf is a workspace manager that will download, install and configure the required software packages
for a development environment.

To list all available leaf commands see *leaf help --list*

== Common leaf scenarios

=== Informational Leaf Commands
*help*::
Displays this page and other help commands. e.g.; *leaf help _COMMAND_*
*version*::
Displays the version of Leaf

=== Initialize a workspace/profile and download a package for your target (see also: *leaf help start*)
*search*::
Search for a package for your target
*setup*::
Setup a workspace (if not created), create/setup a profile and download packages
*shell*::
Enter into a shell configured for your profile and environment

=== Manage your Profile
*status*::
List your current profiles and their status
*select*::
Switch between multiple profiles
*update*::
Update(upgrade/downgrade) a profile to another version of a package
*profile*::
Manage your profiles: rename, delete, sync

=== Configure a profile to use the source or binary version of a package (see also: *leaf help source*)
*getsrc*::
Switch to the source version of a package (if available)

=== Manage your Leaf Environment::
*colors*::
Change to a different color theme
*env*::
Create, set, and remove environment variables
*config*::
Manage the configuration of leaf

=== Manage the repositories for your packages. (see also: *leaf help streams*)
*remote*::
Add, remove and manage the list of remote repositories

== Options

*leaf* [*--non-interactive*] [*-w* _WORKSPACE_] *_COMMAND_* [*-v*|*-q*] [options...]

*leaf* *-V|--version* # Display version

*leaf* [*_COMMAND_*] *-h|--help* # Display help

=== Optional arguments for all commands
*-v, --verbose*::
increase the level of logging for the command
*-q, --quiet*::
remove all command output except meaningful information
*--non-interactive*::
answer the default choice to every question asked
*-w, --workspace _WORKSPACE_*::
use the specified workspace path
