= leaf-init(1)

== NAME

leaf-init - initialize a leaf workspace for download and configuration of a development environment.

== SYNOPSIS

*leaf* *init*

== DESCRIPTION

*leaf init* command is a low level command used to create a *leaf* workspace.

If the *-w|--workspace* option is set, it will be used to determine the workspace location, otherwise
the workspace location will be the current directory.

A *leaf* workspace is composed of:

  - a *leaf-workspace.json* file which stores all the workspace/profile specific configuration (packages,
  environment variables). It can typically be stored in configuration management, in order to share
  a workspace configuration among a development team.

  - a *leaf-data* folder, automatically managed by *leaf* commands to build a tree of *leaf*
  packages according to the current workspace profiles configuration. The content is specific to a
  given system, and will typically ignored in configuration management system
  (i.e.; *.gitignore* file)

*leaf init* is invoked as part of *leaf setup*, if a workspace has not been created in the users
current directory.

== SEE ALSO

*leaf setup*
