= leaf-remote(1)

== NAME

leaf-remote - configure remote package repositories

== SYNOPSIS

*leaf* *remote* [*list*]

*leaf* *remote* *add* _ALIAS_ _URL_ *--insecure*|*--gpg* _GPGKEY_

*leaf* *remote* *remove* _ALIAS_

*leaf* *remote* *enable* _ALIAS_

*leaf* *remote* *disable* _ALIAS_

*leaf* *remote* *fetch*

== DESCRIPTION

*leaf remote* command allows to manage remotes. A remote is a package repository, i.e. a location from which leaf is 
installing packages.

Remotes are configured in the main *leaf* configuration file (see *leaf config*).

== SUB-COMMANDS

*list*::

This command lists the configured remotes. This is the default command if the command name is omitted.
+
Depending on the *-q*|*-v* options, the output information is:
+
  - default: displays a table with _ALIAS_, _URL_ and enable/disable state for each remote entry.
  - *-v*: as above, plus the fetched state (has this remote being fetched yet) and the time it was fetched for the last time
  - *-q*: displays only _ALIAS_ list

*add*::

This command adds a remote to the user configuration. To add a remote, you need to specify:
+
  - the remote _ALIAS_: a user defined name used to identify this remote in other commands
  - the remote _URL_: the URL to the remote index file
  - the security option: either *--insecure* or *--gpg*; see below

*remove*::

This commands removes the _ALIAS_ remote from the user configuration.

*enable*::

This commands enables the _ALIAS_ remote in the user configuration; this remote will be queried in all the remote fetch operations.

*disable*::

This commands disables the _ALIAS_ remote in the user configuration; this remote will _NOT_ be queried in any remote fetch operation.

*fetch*::

This commands triggers the remote fetch operation: package information is retrieved from all enabled remotes in the configuration.
This is the packages information that is displayed in *leaf search* command.

== OPTIONS

_ALIAS_::

A user defined name used to identify the remote in all remote related *leaf* commands. This name must be unique.

_URL_::

URL to the remote index file. _https:_, _http:_ and _file:_ protocols are supported.

*--insecure*::

When adding a remote, specifies that no index signature verification need to be performed.

*--gpg* _GPGKEY_::

When adding a remote, specifies that index needs to be verified as signed by the key identified with _GPGKEY_ fingerprint.

== EXAMPLES

List remotes::

*leaf remote*

List remotes with more details::

*leaf remote list -v*

Add remote::

*leaf remote add myremote http://myserver.org/path/to/index.json --gpg 0123456789ABCDEF*

Add remote (insecure)::

*leaf remote add myremote-insecure http://myserver.org/path/to/index.json --insecure*

Remove remote::

*leaf remote remove myremote*

Enable remote::

*leaf remote enable myremote*

Disable remote::

*leaf remote disable myremote*

Fetch remote information::

*leaf remote fetch*

== BEHAVIOR

The package information read from enabled remotes is stored in the *leaf* cache (see *leaf config*).

As the package information fetch is an important part of the *leaf* workflows, the *leaf remote fetch* is implicit and automatically triggered
by commands that are related to remote available packages (e.g. *leaf search*, *leaf setup*, *leaf package install*, etc). This smart
remote fetch is triggered only if the cache is considered as invalid.

The remote cache is considered as invalid if:

  - remotes were never fetched
  - the remotes configuration has changed since the last fetch (something added, removed, enabled or disabled)
  - the current cache information is more than 24 hours old

Note that the *leaf remote fetch* operation forces a remote fetch operation immediately, whatever if the cache is considered to be still valid or not.

== SEE ALSO

*leaf config*, *leaf search*
