= leaf-colors(1)

== NAME

leaf-colors - support for color themes in leaf

== DESCRIPTION

The output of some *leaf* commands is highlighted with some colors. The purpose of this document is to
explain how these colors can be customized in order to fit better with your terminal colors.

== Configuration file

The colors configuration is done in the *themes.ini* configuration file. This file is located in the *leaf* configuration
folder (see *leaf config* documentation).

== Themes

Colors can be gathered by "themes". The purpose of a theme is to set a collection of colors, and then you can switch
from a colors collection to another by simply changing the active theme.

In the configuration file, themes are gathered by sections. A section is identified by its header (*[NAME]*) and 
a list of _key=value_ properties.

There is a special section called *[DEFAULT]* which configured the default theme behavior.
This section must always be present in the *themes.ini* file. The coloring behavior will be that if a given property _key_ 
is not defined in the selected theme, it will fallback to its value in the *[DEFAULT]* section.

== Properties

Here is the list of the supported values for property _key_, in a given theme definition.
Except the *selected* key, all others are a color/style definition (see next chapter)

=== selected

Only used in the *[DEFAULT]* theme. This property identifies the active theme (identifying the theme section *[NAME]*)

=== error

All the *leaf* error messages

=== label

Text labels in tables (everything that is not a property value)

=== table_separator

Table lines

=== tag.XXX

Keyword for *XXX* tag (used in *leaf search* and *leaf package list*)

=== remote_disabled

Disabled entry when listing remotes (see *leaf remote*)

=== profile_current

Current entry when listing profiles (see *leaf status* and *leaf profile*)

== Colors and styles

Values for the above property keys can be a combination of a foreground color, a background color and a style

=== Foreground colors

Available foreground colors are: *F_BLACK*, *F_RED*, *F_GREEN*, *F_YELLOW*, *F_BLUE*, *F_MAGENTA*, *F_CYAN*, *F_WHITE*

Some other values are fairly well supported, but may be not on some specific configurations: *F_LIGHTBLACK*, *F_LIGHTRED*, *F_LIGHTGREEN*, *F_LIGHTYELLOW*, *F_LIGHTBLUE*, *F_LIGHTMAGENTA*, *F_LIGHTCYAN*, *F_LIGHTWHITE*

=== Background colors

Available background colors are: *B_BLACK*, *B_RED*, *B_GREEN*, *B_YELLOW*, *B_BLUE*, *B_MAGENTA*, *B_CYAN*, *B_WHITE*

Some other values are fairly well supported, but may be not on some specific configurations: *B_LIGHTBLACK*, *B_LIGHTRED*, *B_LIGHTGREEN*, *B_LIGHTYELLOW*, *B_LIGHTBLUE*, *B_LIGHTMAGENTA*, *B_LIGHTCYAN*, *B_LIGHTWHITE*

=== Styles

Available style values are:

*NORMAL*::

Default fond rendering

*BRIGHT*::

Highlighted (bold) font

*DIM*::

Lowlighted (thin) font

[[X1]]
EXAMPLES
--------
Here is an example of a *[DEFAULT]* section content:

  [DEFAULT]
  selected = DEFAULT
  error = BRIGHT + F_RED
  label = BRIGHT
  table_separator = F_LIGHTBLACK
  tag.current = F_GREEN
  tag.installed = F_GREEN
  tag.latest = F_CYAN
  remote_disabled = F_LIGHTBLACK
  profile_current = F_GREEN

== SEE ALSO

*leaf config*, *leaf search*, *leaf status*, *leaf profile*, *leaf package*, *leaf remote*
