= leaf-config(1)

== NAME

leaf-config - configure and customize leaf options

== SYNOPSIS

*leaf* *config* [*--root* _PACKAGES_ROOT_]

== DESCRIPTION

*leaf config* allows users to configure the leaf tool behavior.

If used without specifying any option, the command will simply outputs the location of the current
configuration file (cf _LEAF_CONFIG_ variable description below).

If used with **--root** option, the command will set the packages install location.

Beyond this command, the leaf tool is also configured through a set of environment variables,
described in this page as well.

== OPTIONS

*--root* _PACKAGES_ROOT_::

Sets the location where packages are installed. A package named _myPackage_1.0_ will be extracted
and installed in the _PACKAGES_ROOT/myPackage_1.0_ folder. Default value for this parameter is
*$HOME/.leaf*

== FOLDER VARIABLES

The following environment variables can be used to configure the different leaf folders.

=== _LEAF_CONFIG_

Location for the leaf configuration folder. Default value is *$HOME/.config/leaf*

_LEAF_CONFIG_ stores the following files/folders:

*config.json*::

The main leaf configuration file which stores:
+
    - the packages root install folder  (cf *--root* option above)
    - the configured remotes list (see *leaf remote*)
    - the user's global environment (see *leaf env*)
+
Global configuration for *leaf* behavior is a combination of the default configuration
file with the *config.json* file present in the user configuration folder (if any).
+
Leaf will search for *config.json* in the following order:
*/etc/leaf/*, */usr/share/leaf/* and then *$HOME/.local/share/leaf/*
+
Modifying the default configuration (e.g. disabling a remote present in the
default configuration) will be stored in the user *config.json* file and
override any default values.
+
Note: in order to reset to the default configuration,
delete the *config.json* file from the user configuration folder.

*themes.ini*::

Contains the colors themes definition (see *leaf help colors* help page)
+
If the *themes.ini* file is not found in the user configuration folder,
leaf will search for *themes.ini* in the following folders:
*/etc/leaf/*, */usr/share/leaf/* and then *$HOME/.local/share/leaf/*
+
Note: in order to reset to the default color theme configuration,
delete the *themes.ini* file from the user configuration folder.

*gpg*::

The gpg keyring folder that contains the keyrings used by leaf for remotes gpg signing.

=== _LEAF_CACHE_

Location of cached information. Default value: *$HOME/.cache/leaf*

It may contain:

    - info from remote indexes
    - package artifacts before install

The content of this folder can be deleted at any time to save disk space.
A warning message will be regularly displayed as soon as this cache size exceeds 5 GB.

=== _LEAF_WORKSPACE_

Location of Leaf workspace. This is similar to main leaf *-w* option.
Note that if both environment variable and *-w* option are set, the option value will be used.

== OPTIONAL SETTINGS VARIABLES

The following environment variables can be used to configure the leaf tool behavior.
Note that these settings can be configured directly in your shell (using .bashrc for example) or
in the *user* variables scope (see *leaf help env*)

=== _LEAF_TIMEOUT_

Duration (in seconds) of the download timeout. Default value is *10*

Timeout that leaf waits to download data when the remote falls into an inactive state.

=== _LEAF_DEBUG_

When set, will print a stack trace to the screen when an error occurs

=== _LEAF_GPG_KEYSERVER_

Overrides default GPG server used to query public keys (see *leaf help remote*)

=== _LEAF_NON_INTERACTIVE_

When set, behaves as if the main leaf *--non-interactive* option was set
(replies the default answer to every asked question)

=== _LEAF_TAR_BIN_

Allows to specify a custom tar program when building leaf packages (see *leaf help build*)

=== _LEAF_DISABLE_LOCKS_

When set, allows concurrent install/uninstall operations (not authorized by default)

=== _LEAF_THEME_

Allows to specific a custom color theme (see *leaf help colors*)

=== _LEAF_PAGER_

For commands which print many lines like the *search* command, a pager is used to get a more 
readable output. By default *less* is used as pager; you can use a custom pager by setting 
_LEAF_PAGER_. Note that setting *LEAF_PAGER=""* (empty string) will disable paging.

== SEE ALSO

*leaf remote*, *leaf env*, *leaf help colors*
