= leaf-package(1)

== NAME

leaf-package - manage packages at low level (out of any workspace)

== SYNOPSIS

*leaf* *package* [*list*] [*-a*] [*-t* _TAG_ ...] [_KEYWORD_ ...]

*leaf* *package* *install* _PACKAGE_ ... [*-k*]

*leaf* *package* *uninstall* _PACKAGE_ ...

*leaf* *package* *upgrade* [_PACKAGE_ ...] [*--clean*]

*leaf* *package* *sync* _PACKAGE_ ...

*leaf* *package* *prereq* _PACKAGE_ ... *--target* _PREREQROOTFOLDER_

*leaf* *package* *deps* _PACKAGE_ ... [*--installed* | *--available* | *--install* | *--uninstall* | *--prereq* | *--upgrade*] [*--env* _KEY_=_VALUE_]

== DESCRIPTION

*leaf package* allows users to manipulate packages at low level (i.e. out of any link to any
workspace). It directly works in the packages root installation folder (see *leaf config*).

The command behavior depends on the used sub-command.

== SUB-COMMANDS

*list*::

Lists the installed packages in the root folder. (default option)
+
The *leaf package list* command behaves like the *leaf search* command; listing installed packages
instead of available packages.

*install*::

Installs the required _PACKAGE_ identifiers to the root folder.
+
The install process follows these steps:
+
  - Builds the dependency chain (see *deps* sub-command)
  - Installs prerequisite packages are installed first (see *prereq* sub-command)
  - Downloads and extracts the packages to the root folder
  - Post-install hooks are executed for any newly installed package (see *leaf help manifest*)

*uninstall*::

Uninstalls the required _PACKAGE_ identifiers from the root folder.
+
The uninstall process follows these steps:
+
  - Builds the dependency chain (see *deps* sub-command)
  - Pre-uninstall hooks are executed for any package to be removed (see *leaf help manifest*)
  - Packages are removed from the root folder

*upgrade*::

If no _PACKAGE_ is specified, looks for all installed _upgradable_ packages (see *leaf help manifest*),
and installs the latest available version for each of them.
+
If a _PACKAGE_ list is specified (only package names are supported), performs the upgrade operation only
for the required packages (whatever they are _upgradable_ or not).

*sync*::

Executes the synchronization hooks for each required _PACKAGE_ identifiers (see *leaf help manifest*)

*prereq*::

Installs the prerequisite packages for each required _PACKAGE_ identifiers (see *leaf help manifest*)
+
Note: Pre-requisite packages are considered volatile, and are not kept in the root packages
folder but installed into a temporary folder that is removed after the install operation (unless the
 *--target* option is used).

*deps*::

Builds a dependency chain for all required _PACKAGE_ identifiers.
+
The build dependency chain depends on the used option (see below)

== OPTIONS

*-a|--all*::

All packages will be displayed (not only the _master_ ones). _master_ packages are top-level
packages (i.e.; package manifests) that contain a dependency matrix of other sub-packages.
+
The default behavior is to only display the _master_ packages.

*-t|--tag* _TAG_::

Restrict the search output to only display packages with at least a tag that is *exactly* matching
the given _TAG_.
+
If _TAG_ is a comma separated list, packages with at least a tag matching *one* of the specified
values will be displayed. (*OR* filtering)
+
The *-t* option can be specified several times. Only packages with tags that are matching *all*
specified _TAG_ values will be displayed. (*AND* filtering)

_KEYWORD_::

Restrict the search output to only display packages matching with the given _KEYWORD_. A given
package is considered to be matching with a _KEYWORD_ if either its _PACKAGE_ identifier or its
description *contains* the _KEYWORD_.
+
If _KEYWORD_ is a comma separated list, packages that are matching with *at least* one of the
specified values will be displayed. (*OR* filtering)
+
Several _KEYWORD_ values can be specified. Only packages that are matching with *all* of the
specified values will be displayed. (*AND* filtering)

Note: The *latest* and *installed* dynamic tags are *not* created by the *leaf package list* command.

_PACKAGE_::

The package identifier.
A package identifier uses the NAME_VERSION format.
+
Note that the *latest* reserved keyword may be used instead of a specific _VERSION_ (i.e., use PACKAGE_latest as a package identifier).
In this case the behavior depends on the command:
+
  - for commands dealing with _available_ packages (e.g., *leaf package install*), it will be mapped to the latest _available_ package
  - for commands dealing with _installed_ packages (e.g., *leaf package deps --installed*), it will be mapped to the latest _installed_ package

*-k|--keep*::

Package install folder is renamed with *_ignored* suffix in the root folder and not deleted after a
failed install. It can be useful to troubleshoot post install hooks behavior when designing package
manifests (see *leaf help manifest*)

*--clean*::

If this option is specified when performing an upgrade operation, old versions of _upgradable_ packages will be proposed to be uninstalled

*--target* _PREREQROOTFOLDER_::

Alternative install folder for prerequisite packages install. TheThis folder won't be deleted after
the install.

*--env* _KEY_=_VALUE_::

Specifies an environment variable to tweak the dynamic dependency chain (as some dependencies are
conditioned with variables).

*--installed*::

Builds the dependency chain of the installed packages related to the specified _PACKAGE_
(only installed packages will be listed)

*--available*::

Builds the dependency chain of the available packages related to the specified _PACKAGE_
(only available packages will be listed)

*--install*::

Builds the dependency chain of the available packages related to the specified _PACKAGE_ that still
need to be installed (already installed packages will be filtered)

*--uninstall*::

Builds the dependency chain of the installed packages related to the specified _PACKAGE_ that can be
safely uninstalled (not required anymore as a dependency of any other remaining installed package)

*--prereq*::

Builds the dependency chain of the available packages related to the specified _PACKAGE_ as
prerequisites

*--upgrade*::

Builds the dependency chain of the available packages that would be installed for upgrading
the specified _PACKAGE_
+
With this option, _PACKAGE_ must be a package name (without version information)

== EXAMPLES

List packages::

*leaf package*

List packages with more details::

*leaf package list -v*

Install package::

*leaf package install myPackage*

Uninstall package::

*leaf package uninstall myPackage*

List package prerequisites dependency::

*leaf package deps myPackage --prereq*

Install package prerequisites::

*leaf package prereq myPackage --target /tmp/prerequisited*

== SEE ALSO

*leaf search*, *leaf config*
