= leaf-getsrc(1)

== NAME

leaf-getsrc - trigger source code fetching for packages

== SYNOPSIS

*leaf* *getsrc*

*leaf* *getsrc* _MODULE_ [*--user*|*--workspace*|*--profile*] [*--disable*|*--binary*|*--source* [_MODE_]]

== DESCRIPTION

*leaf getsrc* command allows users to toggle the required module in source mode, and to trigger the
source code fetching operation for a module.

If used without specifying any _MODULE_, the command will return all available source modules within
the current profile.

If used with a _MODULE_ parameter, the command will toggle the corresponding feature in source
mode, and trigger the fetching operation (specific for each module).

== OPTIONS

_MODULE_::

A source module identifier. List of available _MODULE_ items is returned by a simple *getsrc* command.

*--user|--workspace|--profile*::

Allows a user to specify which scope needs to be configured with the
feature corresponding to the required source _MODULE_. Allows a user to toggle a feature across all
workspaces (if *--user* is used), across all profiles of a given workspace (if *--workspace* is
used), or specifically to the current profile (if *--profile* is used; default if not specified).

*--source* [_MODE_]::

Toggles source mode for specified source module.
This is as well the default behavior if neither *--source* nor *--disable* option is specified.
+
Some source module may provide different source modes (e.g. to switch to an alternative branch).
In this case the _MODE_ parameter can be used to specify the source mode to be used (e.g. *--source master*).

*--disable*|*--binary*::

Allows a user to get back to binary mode instead of source code mode.

== EXAMPLES

Get source modules list::

*leaf getsrc*

Trigger source code fetching::

*leaf getsrc mymodule*

Toggle another source mode (e.g. use master branch instead of version tag)::

*leaf getsrc mymodule --source master*

Get back to binary mode::

*leaf getsrc mymodule --disable*

== BEHAVIOR

As an high level command, using *leaf getsrc*
is equivalent to chaining the following steps:

*leaf feature list*::

Verifies if the feature corresponding to the required source module exist. It *must* have
the same name that the _MODULE_, with a *-src* suffix (will be called _MODULE_FEATURE_).

*leaf feature query _MODULE_FEATURE_*::

Then the command verifies if the feature is already toggled in source mode.

*leaf feature toggle _MODULE_FEATURE_ source*::

If necessary, the command toggles the feature in source mode.

*leaf profile sync*::

If necessary (if the feature value changed), the profile provisioning is triggered to update the
*leaf-data* structure.

source fetching operation trigger::

The last step is to trigger the source fetching operation. It is assumed to be handled by a
sync hook provided by any source package that will be installed once the relevant feature is toggled.

== SEE ALSO

*leaf feature*, *leaf profile*
